GET http://127.0.0.1:3000/tasks?limite=2

###
POST http://127.0.0.1:3000/tasks
Content-Type: application/json

{
    "title": "coquito",
    "descripcion": "lorem dolor",
    "fecha": "13 marzo"
}

###
GET http://127.0.0.1:3000/tasks/3

###
PUT http://127.0.0.1:3000/tasks/1
Content-Type: application/json

{
    "title": "tarea 2",
    "descripcion": "lorem dolor"
}

###
DELETE http://127.0.0.1:3000/tasks

###
PATCH http://127.0.0.1:3000/tasks

###
GET http://127.0.0.1:3000/notfound

###
GET http://127.0.0.1:3000/greet?name=willy&age=21